apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: build-suite-test-application-wukb
    appstudio.openshift.io/component: test-component-pac-ions
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: test-component-pac-ions
  namespace: build-e2e-mdfw
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_Michkov-test_devfile-sample-hello-world
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/Michkov-test/devfile-sample-hello-world
