apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-pac-ions
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-pac-ions
    app.kubernetes.io/part-of: build-suite-test-application-wukb
  name: test-component-pac-ions
  namespace: build-e2e-mdfw
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-pac-ions
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-pac-ions
    spec:
      containers:
      - image: quay.io/mkovarik/test-images
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
